/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation(project(":hudi-common"))
    implementation(project(":hudi-hadoop-mr-bundle"))
    implementation(project(":hudi-sync-common"))
    implementation(project(":hudi-gcp"))
    implementation("com.google.cloud:google-cloud-bigquery:2.10.4")
    implementation("org.apache.parquet:parquet-avro:1.10.1")
    implementation("org.apache.avro:avro:1.8.2")
}

description = "hudi-gcp-bundle"
