/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation("org.scala-lang:scala-library:2.11.12")
    implementation(project(":hudi-client-common"))
    implementation(project(":hudi-spark-client"))
    implementation(project(":hudi-common"))
    implementation(project(":hudi-hadoop-mr"))
    implementation(project(":hudi-hive-sync"))
    implementation(project(":hudi-sync-common"))
    implementation(project(":hudi-spark-common_2.11"))
    implementation(project(":hudi-spark2_2.11"))
    implementation(project(":hudi-spark2-common"))
    implementation("org.apache.logging.log4j:log4j-api:2.17.2")
    implementation("org.apache.logging.log4j:log4j-core:2.17.2")
    implementation("org.apache.logging.log4j:log4j-1.2-api:2.17.2")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.6.7")
    implementation("com.fasterxml.jackson.module:jackson-module-scala_2.11:2.6.7.1")
    implementation("org.apache.curator:curator-framework:2.7.1")
    implementation("org.apache.curator:curator-client:2.7.1")
    implementation("org.apache.curator:curator-recipes:2.7.1")
    testImplementation("org.apache.spark:spark-sql_2.11:2.4.4")
    testImplementation("org.apache.spark:spark-core_2.11:2.4.4")
    testImplementation("org.apache.spark:spark-catalyst_2.11:2.4.4")
    testImplementation(project(":hudi-client-common"))
    testImplementation(project(":hudi-spark-client"))
    testImplementation(project(":hudi-common"))
    testImplementation(project(":hudi-java-client"))
    testImplementation("org.scalatest:scalatest_2.11:3.0.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.2")
    testImplementation("org.mockito:mockito-junit-jupiter:3.3.3")
    testImplementation("org.junit.platform:junit-platform-runner:1.7.2")
    testImplementation("org.junit.platform:junit-platform-suite-api:1.7.2")
    testImplementation("org.slf4j:slf4j-api:1.7.30")
    testImplementation("org.apache.hadoop:hadoop-hdfs:2.10.1")
    compileOnly("org.apache.avro:avro:1.8.2")
    compileOnly("org.apache.parquet:parquet-avro:1.10.1")
    compileOnly("org.apache.spark:spark-core_2.11:2.4.4")
    compileOnly("org.apache.spark:spark-sql_2.11:2.4.4")
    compileOnly("org.apache.spark:spark-hive_2.11:2.4.4")
    compileOnly("org.apache.hadoop:hadoop-client:2.10.1")
    compileOnly("org.apache.hadoop:hadoop-common:2.10.1")
    compileOnly("org.apache.hive:hive-exec:2.3.1")
    compileOnly("org.apache.hive:hive-jdbc:2.3.1")
    compileOnly("org.apache.hive:hive-metastore:2.3.1")
    compileOnly("org.apache.hive:hive-common:2.3.1")
}

description = "hudi-spark_2.11"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
