/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation(project(":hudi-common"))
    implementation(project(":hudi-client-common"))
    implementation(project(":hudi-flink-client"))
    implementation(project(":hudi-flink1.14.x"))
    implementation(project(":hudi-flink"))
    implementation(project(":hudi-hadoop-mr"))
    implementation(project(":hudi-hive-sync"))
    implementation(project(":hudi-timeline-service"))
    implementation("javax.servlet:javax.servlet-api:3.1.0")
    implementation("org.apache.flink:flink-hadoop-compatibility_2.11:1.14.5")
    implementation("org.apache.flink:flink-parquet_2.11:1.14.5")
    implementation("org.apache.flink:flink-json:1.14.5")
    implementation("org.apache.parquet:parquet-hadoop:1.12.2")
    implementation("org.apache.parquet:parquet-avro:1.12.2")
    implementation("org.apache.parquet:parquet-column:1.12.2")
    implementation("org.apache.parquet:parquet-common:1.12.2")
    implementation("org.apache.parquet:parquet-encoding:1.12.2")
    implementation("org.apache.parquet:parquet-format-structures:1.12.2")
    implementation("org.apache.parquet:parquet-jackson:1.12.2")
    implementation("org.apache.avro:avro:1.10.0")
    implementation("joda-time:joda-time:2.9.9")
    implementation("org.eclipse.jetty:jetty-server:9.4.15.v20190215")
    implementation("org.eclipse.jetty:jetty-util:9.4.15.v20190215")
    implementation("org.eclipse.jetty:jetty-webapp:9.4.15.v20190215")
    implementation("org.eclipse.jetty:jetty-http:9.4.15.v20190215")
    implementation("com.esotericsoftware:kryo-shaded:4.0.2")
    implementation("com.fasterxml.jackson.core:jackson-core:2.6.7")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.6.7.3")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.6.7")
    compileOnly("org.apache.hive:hive-service:2.3.1")
    compileOnly("org.apache.hive:hive-exec:2.3.1")
    compileOnly("org.apache.hive:hive-metastore:2.3.1")
    compileOnly("org.apache.hive:hive-jdbc:2.3.1")
    compileOnly("org.apache.hive:hive-common:2.3.1")
    compileOnly("org.datanucleus:datanucleus-core:5.0.1")
    compileOnly("org.datanucleus:datanucleus-api-jdo:5.0.1")
    compileOnly("org.apache.thrift:libfb303:0.9.3")
    compileOnly("org.apache.orc:orc-core:1.6.0")
}

description = "hudi-flink1.14-bundle"
