/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation(project(":hudi-common"))
    implementation("org.apache.logging.log4j:log4j-api:2.17.2")
    implementation("org.apache.logging.log4j:log4j-core:2.17.2")
    implementation("org.apache.logging.log4j:log4j-1.2-api:2.17.2")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.6.7")
    implementation("com.fasterxml.jackson.core:jackson-core:2.6.7")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.6.7.3")
    implementation("org.apache.httpcomponents:fluent-hc:4.4.1")
    implementation("io.javalin:javalin:2.8.0")
    implementation("com.beust:jcommander:1.72")
    implementation("org.rocksdb:rocksdbjni:5.17.2")
    testImplementation("org.apache.hadoop:hadoop-hdfs:2.10.1")
    testImplementation("org.apache.hadoop:hadoop-common:2.10.1")
    testImplementation(project(":hudi-common"))
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.2")
    testImplementation("org.mockito:mockito-junit-jupiter:3.3.3")
    compileOnly("org.apache.hadoop:hadoop-client:2.10.1")
}

description = "hudi-timeline-service"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
