/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation(project(":hudi-hadoop-mr-bundle"))
    implementation("org.apache.parquet:parquet-avro:1.10.1")
    implementation("org.apache.avro:avro:1.8.2")
    implementation("com.google.guava:guava:12.0.1")
    implementation("commons-lang:commons-lang:2.6")
    implementation("com.google.protobuf:protobuf-java:2.5.0")
}

description = "hudi-trino-bundle"
