/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation(project(":hudi-client-common"))
    implementation("org.apache.parquet:parquet-column:1.12.2")
    testImplementation(project(":hudi-common"))
    testImplementation(project(":hudi-client-common"))
    testImplementation(project(":hudi-hadoop-mr"))
    testImplementation("org.apache.hbase:hbase-testing-util:2.4.9")
    testImplementation("org.apache.hive:hive-exec:2.3.1")
    testImplementation("org.apache.hive:hive-metastore:2.3.1")
    testImplementation("org.apache.flink:flink-test-utils_2.11:1.14.5")
    testImplementation("org.apache.flink:flink-runtime:1.14.5")
    testImplementation("org.apache.flink:flink-streaming-java_2.11:1.14.5")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.2")
    testImplementation("org.mockito:mockito-junit-jupiter:3.3.3")
    testImplementation("org.junit.platform:junit-platform-runner:1.7.2")
    testImplementation("org.junit.platform:junit-platform-suite-api:1.7.2")
    testImplementation("org.junit.platform:junit-platform-commons:1.7.2")
    compileOnly("org.apache.flink:flink-streaming-java_2.11:1.14.5")
    compileOnly("org.apache.flink:flink-clients_2.11:1.14.5")
    compileOnly("org.apache.flink:flink-hadoop-compatibility_2.11:1.14.5")
    compileOnly("org.apache.flink:flink-table-common:1.14.5")
    compileOnly("org.apache.flink:flink-table-runtime_2.11:1.14.5")
    compileOnly("org.apache.flink:flink-parquet_2.11:1.14.5")
    compileOnly("org.apache.flink:flink-avro:1.14.5")
    compileOnly("org.apache.parquet:parquet-avro:1.12.2")
}

description = "hudi-flink-client"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
