/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation(project(":hudi-kafka-connect"))
    implementation(project(":hudi-java-client"))
    implementation(project(":hudi-utilities_2.11"))
    implementation(project(":hudi-common"))
    implementation(project(":hudi-hive-sync"))
    implementation(project(":hudi-spark-common_2.11"))
    implementation("org.apache.avro:avro:1.8.2")
    implementation("org.apache.parquet:parquet-avro:1.10.1")
    implementation("com.google.protobuf:protobuf-java:3.17.3")
    compileOnly("org.apache.hadoop:hadoop-common:2.10.1")
    compileOnly("org.apache.hadoop:hadoop-auth:2.10.1")
    compileOnly("org.apache.hive:hive-service:2.3.1")
    compileOnly("org.apache.hive:hive-service-rpc:2.3.1")
    compileOnly("org.apache.hive:hive-jdbc:2.3.1")
    compileOnly("org.apache.hive:hive-metastore:2.3.1")
    compileOnly("org.apache.hive:hive-common:2.3.1")
}

description = "hudi-kafka-connect-bundle"
