/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation(project(":hudi-common"))
    implementation(project(":hudi-client-common"))
    implementation(project(":hudi-flink-client"))
    implementation(project(":hudi-hadoop-mr"))
    implementation(project(":hudi-hive-sync"))
    implementation(project(":hudi-sync-common"))
    implementation(project(":hudi-flink"))
    implementation("org.apache.flink:flink-streaming-java_2.11:1.14.5")
    implementation("org.apache.flink:flink-clients_2.11:1.14.5")
    implementation("org.apache.flink:flink-connector-kafka_2.11:1.14.5")
    implementation("org.apache.kafka:kafka-clients:2.0.0")
    implementation("org.apache.flink:flink-hadoop-compatibility_2.11:1.14.5")
    implementation("org.apache.parquet:parquet-hadoop:1.11.1")
    implementation("org.apache.avro:avro:1.10.0")
    implementation("org.apache.hadoop:hadoop-mapreduce-client-core:2.10.1")
    implementation("com.beust:jcommander:1.72")
    implementation("com.twitter:bijection-avro_2.11:0.9.7")
    implementation("joda-time:joda-time:2.5")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.2")
    testImplementation(project(":hudi-common"))
    testImplementation(project(":hudi-client-common"))
    testImplementation(project(":hudi-flink-client"))
    testImplementation("org.apache.flink:flink-test-utils_2.11:1.14.5")
    testImplementation("org.apache.flink:flink-runtime:1.14.5")
    testImplementation("org.apache.flink:flink-streaming-java_2.11:1.14.5")
    testImplementation("org.apache.flink:flink-table-runtime_2.11:1.14.5")
    testImplementation("org.apache.flink:flink-json:1.14.5")
    testImplementation("org.apache.flink:flink-csv:1.14.5")
    testImplementation("org.apache.parquet:parquet-avro:1.11.1")
    compileOnly("org.apache.flink:flink-parquet_2.11:1.14.5")
    compileOnly("org.apache.flink:flink-json:1.14.5")
    compileOnly("org.apache.flink:flink-table-common:1.14.5")
    compileOnly("org.apache.flink:flink-table-runtime_2.11:1.14.5")
    compileOnly("org.apache.flink:flink-table-planner_2.11:1.14.5")
    compileOnly("org.apache.flink:flink-statebackend-rocksdb_2.11:1.14.5")
    compileOnly("org.apache.hive:hive-exec:2.3.1")
}

description = "hudi-examples-flink"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
