/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation("io.acryl:datahub-client:0.8.31")
    implementation("org.apache.httpcomponents:fluent-hc:4.4.1")
    implementation("org.apache.httpcomponents:httpcore:4.4.1")
    implementation("org.apache.httpcomponents:httpclient:4.4.1")
    implementation("org.apache.httpcomponents:httpasyncclient:4.1.5")
    implementation("org.apache.httpcomponents:httpcore-nio:4.4.1")
    implementation("org.apache.logging.log4j:log4j-api:2.17.2")
    implementation("org.apache.logging.log4j:log4j-core:2.17.2")
    implementation("org.apache.logging.log4j:log4j-1.2-api:2.17.2")
    implementation(project(":hudi-common"))
    implementation(project(":hudi-sync-common"))
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.2")
    testImplementation("org.mockito:mockito-junit-jupiter:3.3.3")
    testImplementation("org.junit.platform:junit-platform-runner:1.7.2")
    testImplementation("org.junit.platform:junit-platform-suite-api:1.7.2")
    compileOnly("org.apache.parquet:parquet-avro:1.10.1")
}

description = "hudi-datahub-sync"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
