/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation(project(":hudi-common"))
    implementation(project(":hudi-hive-sync"))
    implementation("org.apache.logging.log4j:log4j-api:2.17.2")
    implementation("org.apache.logging.log4j:log4j-core:2.17.2")
    implementation("org.apache.logging.log4j:log4j-1.2-api:2.17.2")
    implementation("com.amazonaws:dynamodb-lock-client:1.1.0")
    implementation("com.amazonaws:aws-java-sdk-cloudwatch:1.12.22")
    implementation("com.amazonaws:aws-java-sdk-dynamodb:1.12.22")
    implementation("com.amazonaws:aws-java-sdk-core:1.12.22")
    implementation("io.dropwizard.metrics:metrics-core:4.1.1")
    implementation("com.amazonaws:aws-java-sdk-glue:1.12.22")
    testImplementation("org.apache.hadoop:hadoop-common:2.10.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.2")
    testImplementation("org.mockito:mockito-junit-jupiter:3.3.3")
    testImplementation("org.junit.platform:junit-platform-runner:1.7.2")
    testImplementation("org.junit.platform:junit-platform-suite-api:1.7.2")
    compileOnly("org.apache.hive:hive-service:2.3.1")
    compileOnly("org.apache.parquet:parquet-avro:1.10.1")
}

description = "hudi-aws"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
