/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation(project(":hudi-common"))
    implementation(project(":hudi-hadoop-mr-bundle"))
    implementation(project(":hudi-datahub-sync"))
    implementation("org.apache.parquet:parquet-avro:1.10.1")
    implementation("org.apache.avro:avro:1.8.2")
}

description = "hudi-datahub-sync-bundle"
