/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation("org.scala-lang:scala-library:2.11.12")
    implementation(project(":hudi-examples-common"))
    implementation(project(":hudi-cli"))
    implementation(project(":hudi-client-common"))
    implementation(project(":hudi-java-client"))
    implementation(project(":hudi-spark-client"))
    implementation(project(":hudi-utilities_2.11"))
    implementation(project(":hudi-spark_2.11"))
    implementation(project(":hudi-spark-common_2.11"))
    implementation(project(":hudi-hadoop-mr"))
    implementation(project(":hudi-timeline-service"))
    implementation("org.apache.parquet:parquet-hadoop:1.10.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.2")
    testImplementation("org.mockito:mockito-junit-jupiter:3.3.3")
    testImplementation(project(":hudi-client-common"))
    testImplementation(project(":hudi-spark-client"))
    compileOnly("org.apache.spark:spark-core_2.11:2.4.4")
    compileOnly("org.apache.spark:spark-sql_2.11:2.4.4")
    compileOnly("org.apache.hadoop:hadoop-auth:2.10.1")
    compileOnly("org.apache.avro:avro:1.8.2")
    compileOnly("org.apache.parquet:parquet-avro:1.10.1")
    compileOnly("org.apache.hive:hive-common:2.3.1")
    compileOnly("org.apache.hive:hive-exec:2.3.1")
}

description = "hudi-examples-spark"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
