/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation(project(":hudi-common"))
    implementation(project(":hudi-utilities_2.11"))
}

description = "hudi-utilities-slim-bundle_2.11"
