/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation(project(":hudi-common"))
    testImplementation(project(":hudi-common"))
    testImplementation("org.apache.hadoop:hadoop-common:2.10.1")
    testImplementation("org.apache.hadoop:hadoop-hdfs:2.10.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.2")
    testImplementation("org.mockito:mockito-junit-jupiter:3.3.3")
    compileOnly("org.apache.avro:avro:1.8.2")
    compileOnly("org.apache.parquet:parquet-avro:1.10.1")
    compileOnly("org.apache.hadoop:hadoop-auth:2.10.1")
    compileOnly("org.apache.hadoop:hadoop-mapreduce-client-core:2.10.1")
    compileOnly("org.apache.hadoop:hadoop-mapreduce-client-common:2.10.1")
    compileOnly("org.apache.hive:hive-jdbc:2.3.1")
    compileOnly("org.apache.hive:hive-exec:2.3.1")
}

description = "hudi-hadoop-mr"
