/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation(project(":hudi-examples-common"))
    implementation(project(":hudi-client-common"))
    implementation(project(":hudi-java-client"))
    implementation("org.apache.parquet:parquet-hadoop:1.10.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.2")
    testImplementation("org.mockito:mockito-junit-jupiter:3.3.3")
    compileOnly("org.apache.parquet:parquet-avro:1.10.1")
}

description = "hudi-examples-java"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
