/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation(project(":hudi-java-client"))
    implementation(project(":hudi-utilities_2.11"))
    implementation(project(":hudi-client-common"))
    implementation(project(":hudi-flink"))
    implementation("org.apache.flink:flink-core:1.14.5")
    implementation("org.apache.flink:flink-hadoop-compatibility_2.11:1.14.5")
    implementation("com.google.protobuf:protobuf-java:3.17.3")
    implementation("org.apache.logging.log4j:log4j-api:2.17.2")
    implementation("org.apache.logging.log4j:log4j-core:2.17.2")
    implementation("org.apache.logging.log4j:log4j-1.2-api:2.17.2")
    implementation("com.fasterxml.jackson.module:jackson-module-scala_2.11:2.6.7.1")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-csv:2.6.7")
    testImplementation(project(":hudi-common"))
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.2")
    testImplementation("org.mockito:mockito-junit-jupiter:3.3.3")
    testImplementation("org.junit.platform:junit-platform-runner:1.7.2")
    testImplementation("org.junit.platform:junit-platform-suite-api:1.7.2")
    testImplementation("org.junit.platform:junit-platform-commons:1.7.2")
    compileOnly("org.apache.kafka:connect-api:2.5.0")
    compileOnly("org.apache.kafka:connect-json:2.5.0")
    compileOnly("org.apache.avro:avro:1.8.2")
    compileOnly("org.apache.hadoop:hadoop-common:2.10.1")
    compileOnly("org.apache.hive:hive-common:2.3.1")
    compileOnly("org.apache.hive:hive-metastore:2.3.1")
}

description = "hudi-kafka-connect"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
