/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation("org.scala-lang:scala-library:2.11.12")
    implementation(project(":hudi-client-common"))
    testImplementation(project(":hudi-common"))
    testImplementation(project(":hudi-client-common"))
    testImplementation(project(":hudi-hadoop-mr"))
    testImplementation("org.apache.hbase:hbase-testing-util:2.4.9")
    testImplementation("org.apache.zookeeper:zookeeper:3.5.7")
    testImplementation("org.apache.hive:hive-exec:2.3.1")
    testImplementation("org.apache.hive:hive-metastore:2.3.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.2")
    testImplementation("org.mockito:mockito-junit-jupiter:3.3.3")
    testImplementation("org.junit.platform:junit-platform-runner:1.7.2")
    testImplementation("org.junit.platform:junit-platform-suite-api:1.7.2")
    testImplementation("org.junit.platform:junit-platform-commons:1.7.2")
    testImplementation("org.awaitility:awaitility:3.1.2")
    compileOnly("org.apache.spark:spark-core_2.11:2.4.4")
    compileOnly("org.apache.spark:spark-sql_2.11:2.4.4")
    compileOnly("org.apache.parquet:parquet-avro:1.10.1")
}

description = "hudi-spark-client"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
