/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation(project(":hudi-common"))
    implementation(project(":hudi-client-common"))
    implementation(project(":hudi-spark-client"))
    implementation(project(":hudi-hive-sync"))
    implementation(project(":hudi-spark-common_2.11"))
    implementation(project(":hudi-spark_2.11"))
    implementation(project(":hudi-spark2_2.11"))
    implementation(project(":hudi-spark2-common"))
    implementation(project(":hudi-utilities_2.11"))
    implementation("org.apache.parquet:parquet-avro:1.10.1")
    implementation("org.apache.htrace:htrace-core:3.1.0-incubating")
    implementation("org.apache.curator:curator-framework:2.7.1")
    implementation("org.apache.curator:curator-client:2.7.1")
    implementation("org.apache.curator:curator-recipes:2.7.1")
    compileOnly("org.apache.hive:hive-service:2.3.1")
    compileOnly("org.apache.hive:hive-service-rpc:2.3.1")
    compileOnly("org.apache.hive:hive-jdbc:2.3.1")
    compileOnly("org.apache.hive:hive-metastore:2.3.1")
    compileOnly("org.apache.hive:hive-common:2.3.1")
}

description = "hudi-utilities-bundle_2.11"
