/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation(project(":hudi-client-common"))
    testImplementation(project(":hudi-common"))
    testImplementation(project(":hudi-client-common"))
    testImplementation(project(":hudi-hadoop-mr"))
    testImplementation("org.apache.hive:hive-exec:2.3.1")
    testImplementation("org.apache.hive:hive-metastore:2.3.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.2")
    testImplementation("org.mockito:mockito-junit-jupiter:3.3.3")
    testImplementation("org.junit.platform:junit-platform-runner:1.7.2")
    testImplementation("org.junit.platform:junit-platform-suite-api:1.7.2")
    testImplementation("org.junit.platform:junit-platform-commons:1.7.2")
    testImplementation("org.apache.hadoop:hadoop-hdfs:2.10.1")
    compileOnly("org.apache.parquet:parquet-avro:1.10.1")
}

description = "hudi-java-client"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
