/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation(project(":hudi-common"))
    implementation(project(":hudi-timeline-service"))
    implementation("joda-time:joda-time:2.9.9")
    implementation("org.apache.logging.log4j:log4j-api:2.17.2")
    implementation("org.apache.logging.log4j:log4j-core:2.17.2")
    implementation("org.apache.logging.log4j:log4j-1.2-api:2.17.2")
    implementation("com.github.davidmoten:hilbert-curve:0.2.2")
    implementation("io.dropwizard.metrics:metrics-graphite:4.1.1")
    implementation("io.dropwizard.metrics:metrics-core:4.1.1")
    implementation("io.dropwizard.metrics:metrics-jmx:4.1.1")
    implementation("io.prometheus:simpleclient:0.8.0")
    implementation("io.prometheus:simpleclient_httpserver:0.8.0")
    implementation("io.prometheus:simpleclient_dropwizard:0.8.0")
    implementation("io.prometheus:simpleclient_pushgateway:0.8.0")
    implementation("org.apache.curator:curator-framework:2.7.1")
    implementation("org.apache.curator:curator-client:2.7.1")
    implementation("org.apache.curator:curator-recipes:2.7.1")
    testImplementation(project(":hudi-common"))
    testImplementation("org.apache.hadoop:hadoop-hdfs:2.10.1")
    testImplementation("org.apache.hadoop:hadoop-common:2.10.1")
    testImplementation("org.awaitility:awaitility:3.1.2")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.2")
    testImplementation("org.mockito:mockito-junit-jupiter:3.3.3")
    testImplementation("org.junit.platform:junit-platform-runner:1.7.2")
    testImplementation("org.junit.platform:junit-platform-suite-api:1.7.2")
    testImplementation("org.junit.platform:junit-platform-commons:1.7.2")
    testImplementation("org.apache.curator:curator-test:2.7.1")
    providedCompile(project(":hudi-aws"))
    compileOnly("org.apache.parquet:parquet-avro:1.10.1")
}

description = "hudi-client-common"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
