/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation(project(":hudi-common"))
    testImplementation("org.apache.flink:flink-runtime_2.11:1.13.6")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.2")
    testImplementation("org.mockito:mockito-junit-jupiter:3.3.3")
    testImplementation("org.junit.platform:junit-platform-runner:1.7.2")
    testImplementation("org.junit.platform:junit-platform-suite-api:1.7.2")
    testImplementation("org.junit.platform:junit-platform-commons:1.7.2")
    compileOnly("org.apache.hadoop:hadoop-common:2.10.1")
    compileOnly("org.apache.flink:flink-table-runtime-blink_2.11:1.13.6")
    compileOnly("org.apache.flink:flink-streaming-java_2.11:1.13.6")
    compileOnly("org.apache.flink:flink-core:1.13.6")
    compileOnly("org.apache.flink:flink-parquet_2.11:1.13.6")
    compileOnly("org.apache.flink:flink-json:1.13.6")
}

description = "hudi-flink1.13.x"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
