/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.6.7")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.6.7.3")
    implementation("com.github.ben-manes.caffeine:caffeine:2.9.1")
    implementation("org.apache.orc:orc-core:1.6.0")
    implementation("org.apache.httpcomponents:fluent-hc:4.4.1")
    implementation("org.apache.httpcomponents:httpclient:4.4.1")
    implementation("org.rocksdb:rocksdbjni:5.17.2")
    implementation("com.esotericsoftware:kryo-shaded:4.0.2")
    implementation("org.apache.hbase:hbase-client:2.4.9")
    implementation("org.apache.hbase:hbase-server:2.4.9")
    implementation("org.lz4:lz4-java:1.8.0")
    testImplementation("org.apache.hadoop:hadoop-common:2.10.1")
    testImplementation("org.apache.hadoop:hadoop-hdfs:2.10.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.2")
    testImplementation("org.mockito:mockito-junit-jupiter:3.3.3")
    testImplementation("com.github.stefanbirkner:system-rules:1.17.2")
    testImplementation("joda-time:joda-time:2.9.9")
    compileOnly("org.apache.avro:avro:1.8.2")
    compileOnly("org.apache.parquet:parquet-avro:1.10.1")
    compileOnly("org.apache.hadoop:hadoop-client:2.10.1")
    compileOnly("org.apache.hadoop:hadoop-hdfs:2.10.1")
}

description = "hudi-common"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
