/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    implementation(project(":hudi-common"))
    implementation(project(":hudi-hadoop-mr"))
    implementation(project(":hudi-sync-common"))
    implementation("org.apache.logging.log4j:log4j-api:2.17.2")
    implementation("org.apache.logging.log4j:log4j-1.2-api:2.17.2")
    implementation("com.beust:jcommander:1.72")
    testImplementation("org.apache.logging.log4j:log4j-core:2.17.2")
    testImplementation("org.apache.hadoop:hadoop-common:2.10.1")
    testImplementation("org.apache.hadoop:hadoop-hdfs:2.10.1")
    testImplementation("org.apache.hive:hive-service:2.3.1")
    testImplementation(project(":hudi-common"))
    testImplementation("org.apache.thrift:libthrift:0.12.0")
    testImplementation("org.apache.spark:spark-sql_2.11:2.4.4")
    testImplementation("org.apache.spark:spark-core_2.11:2.4.4")
    testImplementation("org.eclipse.jetty.aggregate:jetty-all:7.6.0.v20120127")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.2")
    testImplementation("org.mockito:mockito-junit-jupiter:3.3.3")
    testImplementation("org.junit.platform:junit-platform-runner:1.7.2")
    testImplementation("org.junit.platform:junit-platform-suite-api:1.7.2")
    testImplementation("org.junit.platform:junit-platform-commons:1.7.2")
    testImplementation("org.apache.hadoop:hadoop-mapreduce-client-common:2.10.1")
    testImplementation("org.apache.hadoop:hadoop-mapreduce-client-core:2.10.1")
    compileOnly("org.apache.parquet:parquet-avro:1.10.1")
    compileOnly("org.apache.hadoop:hadoop-common:2.10.1")
    compileOnly("org.apache.hadoop:hadoop-client:2.10.1")
    compileOnly("org.apache.hadoop:hadoop-hdfs:2.10.1")
    compileOnly("org.apache.hadoop:hadoop-auth:2.10.1")
    compileOnly("org.apache.hive:hive-jdbc:2.3.1")
    compileOnly("org.apache.hive:hive-metastore:2.3.1")
    compileOnly("org.apache.hive:hive-common:2.3.1")
}

description = "hudi-hive-sync"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
