/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.hudi.java-conventions")
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.2")
    testImplementation("org.mockito:mockito-junit-jupiter:3.3.3")
    testImplementation("org.junit.platform:junit-platform-runner:1.7.2")
    testImplementation("org.junit.platform:junit-platform-suite-api:1.7.2")
}

description = "hudi-spark2-common"
